let a = prompt("Як вас величать?")
console.log(a)
alert("Здраствуйте " + a)
let b = prompt("Ваш возраст? " + a)
console.log(b)
alert("Вы указали возраст  " + b)
let c = prompt("Ваше место рождения?")
console.log(c)
alert("Вы родились в " + c)
let d = prompt("Доверяете ли вы интернет магазинам?")
alert("Этот ответ не засчитывается на f12")
let q = prompt("Ваш пол?")
console.log(q)
alert("Ваш пол  " + q)
let w = prompt("Имеете ли высшее образование?")
alert("Этот ответ не засчитывается на f12")
let e = prompt("Вы женаты?")
console.log(e)
alert("Я на Самсунге)")
let r = prompt("Первая группа учится лучше чем вторая???")
console.log(r)
alert("Этот ответ я засчитаю...")
let t = prompt("Какая фирма одежды вам нравится больше, здесь гопников нет")
console.log(t)
alert("Ваша любимая фирма одежды " + t)
let y = prompt("Да")
alert("фвыаывпаывпчспы")